version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - appnet
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - appnet
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mental_health_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/tinhthan.sql:/docker-entrypoint-initdb.d/tinhthan.sql
    networks:
      - appnet
volumes:
  db_data:
networks:
  appnet:
    driver: bridge
